on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🌻 Format Archives
        run: yarn prettier --config ./.prettierrc --ignore-path ./.prettierignore  --write ./src/

      - name: 🚀 Publish app
        run: yarn build
